//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirportLibrary.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket_Passenger
    {
        public int IDTicket { get; set; }
        public string NumberTicket { get; set; }
        public int BookingID { get; set; }
        public int PassengerID { get; set; }
        public int FlightID { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Flight Flight { get; set; }
        public virtual Passenger Passenger { get; set; }
    }
}
